spring:
  profiles:
    active: dev
  application:
    name: service-core


server:
  port: 8110
#  address: 192.168.5.1

#mybatis:
#  mapper-locations: classpath:/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/xh/srb/core/mapper/xml/*.xml

