spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.156.191.5:3306/srb_core?serverTimezone=Asia/Shanghai
    username: srb
    password: srb
  profiles:
    active: dev
  application:
    name: service-core
  redis:
    host: localhost
    port: 6379
    database: 0
#    password: 123456 #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

server:
  port: 8110
  address: localhost
#mybatis:
#  mapper-locations: classpath:/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/xh/srb/core/mapper/xml/*.xml

