spring:
  profiles:
    active: dev
  application:
    name: service-core
  cloud:
    nacos:
      discovery:
        server-addr: 82.156.191.5:8848

server:
  port: 8110
  address: localhost
#mybatis:
#  mapper-locations: classpath:/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/xh/srb/core/mapper/xml/*.xml

