server:
  port: 8120

spring:
  application:
    name: service-sms
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 82.156.191.5:8848

#阿里云短信
aliyun:
  sms:
    region-id: cn-hangzhou
    key-id: 你的keyid
    key-secret: 你的keysecret
    template-code: 您的验证码为[%%%%]
    sign-name: xh