server:
  port: 8120

spring:
  application:
    name: service-sms
  profiles:
    active: dev


#阿里云短信
aliyun:
  sms:
    region-id: cn-hangzhou
    key-id: 你的keyid
    key-secret: 你的keysecret
    template-code: 您的验证码为[%%%%]
    sign-name: xh

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置
  sentinel:
    enabled: true

logging:
  level:
    com.xh.srb.sms.client.CoreUserInfoClient: DEBUG #以什么级别监控哪个接口